### ISSUE TITLE
Change .gitignore

### ISSUE THREAD

**Issue by tekknolagi** [bencw99/RoboticsGameAPI#6]
You should probably change your .gitignore so you don't accidentally check in files that you don't mean to check in. Like .classpath, etc.

**Comment by niharmitra** [comment]
We keep the .classpath and .project files on purpose to make importing into Eclipse easier, and to prevent some bugs that occurred previously with Eclipse and Freyja.

**Comment by tekknolagi** [comment]
Fair.
